name: usemain
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.0.14
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: dingding
      fonts:
        - asset: assets/fonts/DingTalk-JinBuTi.ttf
    - family: wordbold
      fonts:
        - asset: assets/fonts/Word-Bold.ttf
